### ISSUE TITLE
/register returns "Unsupported operation." but partly works anyway.

### ISSUE THREAD

**Issue by trautvetter** [stormpath/stormpath-sdk-java#1351]
The built in SDK endpoint /register returns an error - "Unsupported operation." but it creates the account in Okta anyway and logs as follows after onValidSubmit() throws an exception.

RegisteredAccountRequestEvent listener is not called.
```
        try {
            validate(request, response, form);
            return onValidSubmit(request, response, form);
        } catch (Exception e) {
            log.warn("Failure to post", e);
            return onErrorSubmit(request, response, form, e);
        }
```
2017-08-17 16:05:06.922  WARN 898472 --- [nio-8080-exec-2] c.s.s.s.m.FormController                 : Failure to post

com.stormpath.sdk.resource.ResourceException: HTTP 501, Stormpath 0 (Unsupported operation.), RequestId oaesC5FuamkSom_Yy7cqZqDvg: 
	at com.stormpath.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:644) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.DefaultDataStore.access$000(DefaultDataStore.java:88) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.DefaultDataStore$2.filter(DefaultDataStore.java:485) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.ProviderAccountResultFilter.filter(ProviderAccountResultFilter.java:31) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.api.ApiKeyQueryFilter.filter(ApiKeyQueryFilter.java:74) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.cache.WriteCacheFilter.filter(WriteCacheFilter.java:90) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.cache.ReadCacheFilter.filter(ReadCacheFilter.java:71) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.api.DecryptApiKeySecretFilter.filter(DecryptApiKeySecretFilter.java:63) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.EnlistmentFilter.filter(EnlistmentFilter.java:42) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:512) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:417) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.directory.OktaDirectory.associateUserWithGroup(OktaDirectory.java:209) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.directory.OktaDirectory.associateUser(OktaDirectory.java:184) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.directory.OktaDirectory.createAccount(OktaDirectory.java:175) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.directory.OktaDirectory.createAccount(OktaDirectory.java:153) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.directory.OktaDirectory.createAccount(OktaDirectory.java:146) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.impl.application.OktaApplication.createAccount(OktaApplication.java:200) ~[stormpath-sdk-impl-2.0.0-okta.jar:2.0.0-okta]
	at com.stormpath.sdk.servlet.mvc.RegisterController.onValidSubmit(RegisterController.java:247) ~[stormpath-sdk-servlet-2.0.0-okta.jar:2.0.0-okta]

**Comment by trautvetter** [comment]
Logs say it's a 501 unsupported. Is this _not_ supposed to work? Is there any documentation of a pure Okta way to do this or work around or fix for this?

**Comment by mraible** [comment]
@bdemers Any ideas on this one?
