### ISSUE TITLE
[1.0.RC3.preview.0] RestException: Unable to execute HTTP request: null

### ISSUE THREAD

**Issue by francisdb** [stormpath/stormpath-sdk-java#146]
We are having these exceptions with message null
```java
Caused by: com.stormpath.sdk.impl.http.RestException: Unable to execute HTTP request: null
	at com.stormpath.sdk.impl.http.httpclient.HttpClientRequestExecutor.executeRequest(HttpClientRequestExecutor.java:265) ~[com.stormpath.sdk.stormpath-sdk-httpclient-1.0.RC3.preview.0.jar:1.0.RC3.preview.0]
	at com.stormpath.sdk.impl.ds.DefaultDataStore.executeRequestGetFullResponse(DefaultDataStore.java:932) ~[com.stormpath.sdk.stormpath-sdk-impl-1.0.RC3.preview.0.jar:1.0.RC3.preview.0]
	at com.stormpath.sdk.impl.ds.DefaultDataStore.executeRequest(DefaultDataStore.java:922) ~[com.stormpath.sdk.stormpath-sdk-impl-1.0.RC3.preview.0.jar:1.0.RC3.preview.0]
	at com.stormpath.sdk.impl.ds.DefaultDataStore.retrieveResponseValue(DefaultDataStore.java:317) ~[com.stormpath.sdk.stormpath-sdk-impl-1.0.RC3.preview.0.jar:1.0.RC3.preview.0]
	at com.stormpath.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:216) ~[com.stormpath.sdk.stormpath-sdk-impl-1.0.RC3.preview.0.jar:1.0.RC3.preview.0]
	at com.stormpath.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:196) ~[com.stormpath.sdk.stormpath-sdk-impl-1.0.RC3.preview.0.jar:1.0.RC3.preview.0]
	at com.stormpath.sdk.impl.resource.AbstractCollectionResource$PaginatedIterator.<init>(AbstractCollectionResource.java:142) ~[com.stormpath.sdk.stormpath-sdk-impl-1.0.RC3.preview.0.jar:1.0.RC3.preview.0]
	at com.stormpath.sdk.impl.resource.AbstractCollectionResource$PaginatedIterator.<init>(AbstractCollectionResource.java:132) ~[com.stormpath.sdk.stormpath-sdk-impl-1.0.RC3.preview.0.jar:1.0.RC3.preview.0]
	at com.stormpath.sdk.impl.resource.AbstractCollectionResource.iterator(AbstractCollectionResource.java:112) ~[com.stormpath.sdk.stormpath-sdk-impl-1.0.RC3.preview.0.jar:1.0.RC3.preview.0]
	at com.stormpath.sdk.impl.account.DefaultAccount.isMemberOfGroup(DefaultAccount.java:262) ~[com.stormpath.sdk.stormpath-sdk-impl-1.0.RC3.preview.0.jar:1.0.RC3.preview.0]
	... 32 common frames omitted
Caused by: java.lang.NullPointerException: null
```

**Comment by lhazlewood** [comment]
Please upgrade to the latest stable release.

**Comment by francisdb** [comment]
Oops, seems that machine still has an old preview. Thanks for pointing that out.
