### ISSUE TITLE
Implementation of remember-me for Stormpath with Spring Boot

### ISSUE THREAD

**Issue by george-hawkins-aa** [stormpath/stormpath-sdk-java#337]
I got remember-me functionality working with Stormpath and Spring Boot. Here are the details of how I did it - and then the details of how it would be nice to do it :smile: 

First I customized the default [`login.html`](https://github.com/stormpath/stormpath-sdk-java/blob/master/extensions/spring/boot/stormpath-thymeleaf-spring-boot-starter/src/main/resources/templates/stormpath/login.html) Thymeleaf template - just above the `<div>` that contains the submit button I added:

```HTML
<div class="form-group group-remember-me">
    <div th:class="'col-sm-8 ' + ${social ? '' : 'col-sm-offset-4'}">
        <input type="checkbox" id="remember" name="remember-me" value="true"/>
        <label for="remember">Remember me</label>
    </div>
</div>
```

Note: the original HTML was copied straight from [`login.html`](https://github.com/stormpath/idsite-src/blob/master/app/views/login.html) in the idsite-src repo. The `name` and `value` attributes were added to match the expectations of [`AbstractRememberMeServices`](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/rememberme/AbstractRememberMeServices.java) and one minor Thymeleaf related change was made.

In my `SpringSecurityWebAppConfig` implementation I added:

```java
// Override the behavior of com.stormpath.spring.config.AbstractStormpathWebMvcConfiguration.stormpathCookieAuthenticationResultSaver().
@Bean(name="stormpathCookieAuthenticationResultSaver")
public Saver<AuthenticationResult> stormpathCookieAuthenticationResultSaver(CookieConfig accountCookieConfig, @Qualifier("stormpathSecureResolver")Resolver<Boolean> secureCookieRequired, AuthenticationJwtFactory authenticationJwtFactory) {
    return new CookieAuthenticationResultSaver(accountCookieConfig, secureCookieRequired, authenticationJwtFactory) {
        @Override
        protected CookieConfig getAccountCookieConfig(HttpServletRequest request) {
            CookieConfig delegate = super.getAccountCookieConfig(request);
            
            boolean remember = Boolean.parseBoolean(request.getParameter(AbstractRememberMeServices.DEFAULT_PARAMETER));
            
            // There's no "forever" value but if required you could set a number of seconds corresponding to decades.
            final int maxAge = remember ? AbstractRememberMeServices.TWO_WEEKS_S : delegate.getMaxAge();
            
            System.err.println("Remember me " + (remember ? "set" : "not set"));
            
            return new DelegatingCookieConfig(delegate) {
                @Override
                public int getMaxAge() {
                    return maxAge;
                }
            };
        }
    };
}
```

And I created the very straightforward accompanying class [`DelegatingCookieConfig`](https://gist.github.com/george-hawkins/67b00b632c78964f5c55#file-delegatingcookieconfig-java).

And that was it - if the user clicks the remember-me checkbox then the max cookie age is set to two weeks (matching the default in `AbstractRememberMeServices`).

---

However it would be nice if you could do it the standard way without adding ones own `CookieAuthenticationResultSaver` implementation.

I.e. I'd like to be able to add the following in my `SpringSecurityWebAppConfig` implementation:

```java
http.rememberMe();
```

However if I do this currently all works well up to a point - if I use the same `login.html` template as before then the logic in `AbstractRememberMeServices.rememberMeRequested(HttpServletRequest, String)` picks out the remember-me parameter properly, but then an exception occurs shortly after, due to the the lack of a `UserDetailsService` instance:

```
java.lang.IllegalStateException: UserDetailsService is required.
    at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter$UserDetailsServiceDelegator.loadUserByUsername(WebSecurityConfigurerAdapter.java:407)
    at org.springframework.security.web.authentication.rememberme.TokenBasedRememberMeServices.onLoginSuccess(TokenBasedRememberMeServices.java:182)
    at org.springframework.security.web.authentication.rememberme.AbstractRememberMeServices.loginSuccess(AbstractRememberMeServices.java:277)
    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.successfulAuthentication(AbstractAuthenticationProcessingFilter.java:323)
    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:245)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
```

---

Thanks for the positive feedback from various people at Stormpath to the various issues I've logged so far. I hope you're not getting sick of them! I can imagine you've got a very hectic schedule at this point in Stormpath's life.

**Comment by dogeared** [comment]
Thanks again for this, @george-hawkins-aa! We will definitely prioritize this against the upcoming work. It will get in - just not sure exactly when. It's a really good feature to have right.

**Comment by george-hawkins-aa** [comment]
Hi @dogeared - thanks for the positive feedback :smile: 

I think it's important if you want to reduce end user friction - being forced to log in more often than they feel necessary may be enough to make some users give up on ones service :disappointed: 

I've put [a project](https://github.com/george-hawkins-aa/stormpath-spring-boot-example) up on Github that demonstrates the logic above. See the [remember me section](https://github.com/george-hawkins-aa/stormpath-spring-boot-example#remember-me) of the README for the details.

![remember me](https://cloud.githubusercontent.com/assets/12233059/11370875/ee371b66-92c5-11e5-8150-6037c5af6888.png)

**Comment by dogeared** [comment]
Hey @george-hawkins-aa - circling back here. We already have this feature in our ID Site hosted/managed login workflow.

I've added this issue to our `1.0` milestone as we want to have parity with features already supported in ID Site.

**Comment by lhazlewood** [comment]
@george-hawkins-aa I just wanted to reiterate how grateful we are for the issues/feedback you give us - it is wonderful!  It really helps us with the development efforts, so thank you!
