### ISSUE TITLE
RuntimeException: javax.crypto.BadPaddingException

### ISSUE THREAD

**Issue by francisdb** [stormpath/stormpath-sdk-java#440]
We have this exception from time to time. I suppose Stormpath should be handling this as a failed authentication instead of throwing it as a runtime exception?

stacktrace for version: 1.0.RC7.4

```
java.lang.RuntimeException: javax.crypto.BadPaddingException: Given final block not properly padded
        at com.stormpath.sdk.impl.security.ApiKeySecretEncryptionService.decrypt(ApiKeySecretEncryptionService.java:124)
        at com.stormpath.sdk.impl.security.ApiKeySecretEncryptionService.decryptBase64String(ApiKeySecretEncryptionService.java:100)
        at com.stormpath.sdk.impl.ds.api.DecryptApiKeySecretFilter.clone(DecryptApiKeySecretFilter.java:128)
        at com.stormpath.sdk.impl.ds.api.DecryptApiKeySecretFilter.filter(DecryptApiKeySecretFilter.java:88)
        at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
        at com.stormpath.sdk.impl.ds.EnlistmentFilter.filter(EnlistmentFilter.java:42)
        at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
        at com.stormpath.sdk.impl.ds.DefaultDataStore.getResourceData(DefaultDataStore.java:286)
        at com.stormpath.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:201)
        at com.stormpath.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:197)
        at com.stormpath.sdk.impl.application.DefaultApplication.getApiKey(DefaultApplication.java:535)
        at com.stormpath.sdk.impl.authc.BasicApiAuthenticator.authenticate(BasicApiAuthenticator.java:55)
        at com.stormpath.sdk.impl.authc.BasicApiAuthenticator.authenticate(BasicApiAuthenticator.java:49)
        at com.stormpath.sdk.impl.oauth.authc.OauthAuthenticationRequestDispatcher.authenticate(OauthAuthenticationRequestDispatcher.java:54)
        at com.stormpath.sdk.impl.application.DefaultApplication.authenticateAccount(DefaultApplication.java:337)
        at com.stormpath.sdk.impl.authc.DefaultApiRequestAuthenticator.execute(DefaultApiRequestAuthenticator.java:82)
        at com.stormpath.sdk.impl.application.DefaultApplication.authenticateApiRequest(DefaultApplication.java:557)
        at ...
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:966)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:824)
        at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:436)
        at javax.crypto.Cipher.doFinal(Cipher.java:2165)
        at com.stormpath.sdk.impl.security.ApiKeySecretEncryptionService.decrypt(ApiKeySecretEncryptionService.java:119)
        ... 59 more
```

**Comment by dogeared** [comment]
Hi @francisdb:

Sorry for the delay in reply here. When you say that you see this exception from time to time, do you have an understanding of the root cause?

I am not sure that we *should* be handling this as a failed authentication. I will bring it to the team on our weekly call, however. I'll post updates here.

**Comment by francisdb** [comment]
@dogeared we have a workaround implemented on our side but still think this should be handled by stormpath...

**Comment by dogeared** [comment]
I've added this to our 1.0 milestone and I will let you know where the team lands on how best to handle it. Thanks!

**Comment by jarias** [comment]
We need to get more details on this ticket to try and resolve it. As @lhazlewood mention the API keys come from our own backend API so there should not be an padding error.

**Comment by francisdb** [comment]
Wherever the input came from, it should just fail authentication, certainly not bleed through a third-party exception

**Comment by mraible** [comment]
Here's the offending code, that throws a `RuntimeException` with `BadPaddingException`. @lhazlewood @dogeared What do you think is the best way to fix this?

```java
    private byte[] decrypt(byte[] encryptedValue) {

        try {

            int ivSize = builder.keySize;
            int ivByteSize = ivSize / BITS_PER_BYTE;

            byte[] iv = new byte[ivByteSize];
            System.arraycopy(encryptedValue, 0, iv, 0, ivByteSize);

            byte[] rawEncryptedValue = new byte[encryptedValue.length - ivByteSize];

            int encryptedSize = encryptedValue.length - ivByteSize;
            System.arraycopy(encryptedValue, ivByteSize, rawEncryptedValue, 0, encryptedSize);

            cipher.init(Cipher.DECRYPT_MODE, key, new IvParameterSpec(iv));
            byte[] plainTxtBytes = cipher.doFinal(rawEncryptedValue);

            return plainTxtBytes;

        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```

**Comment by lhazlewood** [comment]
We encrypt the values during transit as an extra precaution (even over TLS connections).  I think a good fallback approach is to re-request, but without message-level encryption this time (but definitely still over TLS).

Ideally we should find out *why* the bad padding occurs - this is abnormal - and fix that instead, but a re-request is a good workaround IMO since this only occurs intermittently and very rarely.

**Comment by francisdb** [comment]
The initial issue still is not solved, we still get the same RuntimeExceptions wrapping BadPaddingException instead of authentication just failing with proper Stormpath exceptions

stacktrace for version: `1.2.2`

```
java.lang.RuntimeException: javax.crypto.BadPaddingException: Given final block not properly padded
    at com.stormpath.sdk.impl.security.ApiKeySecretEncryptionService.decrypt(ApiKeySecretEncryptionService.java:124)
    at com.stormpath.sdk.impl.security.ApiKeySecretEncryptionService.decryptBase64String(ApiKeySecretEncryptionService.java:100)
    at com.stormpath.sdk.impl.ds.api.DecryptApiKeySecretFilter.clone(DecryptApiKeySecretFilter.java:129)
    at com.stormpath.sdk.impl.ds.api.DecryptApiKeySecretFilter.filter(DecryptApiKeySecretFilter.java:89)
    at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
    at com.stormpath.sdk.impl.ds.EnlistmentFilter.filter(EnlistmentFilter.java:42)
    at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
    at com.stormpath.sdk.impl.ds.DefaultDataStore.getResourceData(DefaultDataStore.java:337)
    at com.stormpath.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:250)
    at com.stormpath.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:246)
    at com.stormpath.sdk.impl.application.DefaultApplication.getApiKey(DefaultApplication.java:620)
    at com.stormpath.sdk.impl.authc.BasicApiAuthenticator.authenticate(BasicApiAuthenticator.java:63)
    at com.stormpath.sdk.impl.authc.BasicApiAuthenticator.authenticate(BasicApiAuthenticator.java:53)
    at com.stormpath.sdk.impl.oauth.authc.OAuthAuthenticationRequestDispatcher.authenticate(OAuthAuthenticationRequestDispatcher.java:53)
    at com.stormpath.sdk.impl.application.DefaultApplication.authenticateAccount(DefaultApplication.java:422)
    at com.stormpath.sdk.impl.authc.DefaultApiRequestAuthenticator.execute(DefaultApiRequestAuthenticator.java:71)
    at com.stormpath.sdk.impl.authc.DefaultApiRequestAuthenticator.authenticate(DefaultApiRequestAuthenticator.java:85)
  ...
javax.crypto.BadPaddingException: Given final block not properly padded
    at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:975)
    at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:833)
    at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
    at javax.crypto.Cipher.doFinal(Cipher.java:2165)
    at com.stormpath.sdk.impl.security.ApiKeySecretEncryptionService.decrypt(ApiKeySecretEncryptionService.java:119)
    at com.stormpath.sdk.impl.security.ApiKeySecretEncryptionService.decryptBase64String(ApiKeySecretEncryptionService.java:100)
    at com.stormpath.sdk.impl.ds.api.DecryptApiKeySecretFilter.clone(DecryptApiKeySecretFilter.java:129)
    at com.stormpath.sdk.impl.ds.api.DecryptApiKeySecretFilter.filter(DecryptApiKeySecretFilter.java:89)
    at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
    at com.stormpath.sdk.impl.ds.EnlistmentFilter.filter(EnlistmentFilter.java:42)
    at com.stormpath.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
    at com.stormpath.sdk.impl.ds.DefaultDataStore.getResourceData(DefaultDataStore.java:337)
    at com.stormpath.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:250)
    at com.stormpath.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:246)
    at com.stormpath.sdk.impl.application.DefaultApplication.getApiKey(DefaultApplication.java:620)
    at com.stormpath.sdk.impl.authc.BasicApiAuthenticator.authenticate(BasicApiAuthenticator.java:63)
    at com.stormpath.sdk.impl.authc.BasicApiAuthenticator.authenticate(BasicApiAuthenticator.java:53)
    at com.stormpath.sdk.impl.oauth.authc.OAuthAuthenticationRequestDispatcher.authenticate(OAuthAuthenticationRequestDispatcher.java:53)
    at com.stormpath.sdk.impl.application.DefaultApplication.authenticateAccount(DefaultApplication.java:422)
    at com.stormpath.sdk.impl.authc.DefaultApiRequestAuthenticator.execute(DefaultApiRequestAuthenticator.java:71)
    at com.stormpath.sdk.impl.authc.DefaultApiRequestAuthenticator.authenticate(DefaultApiRequestAuthenticator.java:85)
```
