### ISSUE TITLE
failing to cache Account when verifying account email

### ISSUE THREAD

**Issue by jeremypitten** [stormpath/stormpath-sdk-java#60]
With cache enabled and using my own account email verification endpoint, which calls com.stormpath.sdk.impl.tenant.DefaultTenant.verifyAccountEmail, the stormpath request succeeds (email confirmation is received) and a response is received but the DefaultCacheStore fails to cache the returned Account details. As a workaround I just catch the exception :

Caused by: java.lang.IllegalArgumentException: Resource data must be materialized to be cached (need more than just an 'href' attribute).
        at com.stormpath.sdk.lang.Assert.isTrue(Assert.java:33) ~[com.stormpath.sdk.stormpath-sdk-api-0.9.1.jar:0.9.1]
        at com.stormpath.sdk.impl.ds.DefaultDataStore.cache(DefaultDataStore.java:433) ~[com.stormpath.sdk.stormpath-sdk-impl-0.9.1.jar:0.9.1]
        at com.stormpath.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:329) ~[com.stormpath.sdk.stormpath-sdk-impl-0.9.1.jar:0.9.1]
        at com.stormpath.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:298) ~[com.stormpath.sdk.stormpath-sdk-impl-0.9.1.jar:0.9.1]
        at com.stormpath.sdk.impl.ds.DefaultDataStore.save(DefaultDataStore.java:294) ~[com.stormpath.sdk.stormpath-sdk-impl-0.9.1.jar:0.9.1]
        at com.stormpath.sdk.impl.tenant.DefaultTenant.verifyAccountEmail(DefaultTenant.java:167) ~[com.stormpath.sdk.stormpath-sdk-impl-0.9.1.jar:0.9.1]

**Comment by antollinim** [comment]
@lhazlewood. This issue has already been solved and released in 1.0.RC3.preview.0. This code is not present in either dev or master though. I see that there are other commits that exist in this release that are not present in dev and master either. Shouldn't we merge the 1.0.RC3.preview.0 tag to dev and master?

**Comment by lhazlewood** [comment]
@antollinim yes, we should - please do so.  Thanks!

**Comment by lhazlewood** [comment]
@antollinim I don't know if you've merged yet or not, but DO NOT merge 1.0.RC3.preview.0 into master or dev yet.

That was an early/test preview release for the upcoming servlet plugin.  I'll merge that in myself via the `servlet-module` branch.

**Comment by antollinim** [comment]
@lhazlewood I haven't done it yet. Thanks for letting me know....
