### ISSUE TITLE
Getting NPE in TokenRevocationRequestEventListener

### ISSUE THREAD

**Issue by markwoon** [stormpath/stormpath-sdk-java#611]
Upgraded to RC9.1 and I'm getting an NPE:

```
java.lang.RuntimeException: Unable to invoke Stormpath controller: Unable to publish request event: null
	at com.stormpath.sdk.servlet.filter.mvc.ControllerFilter.filter(ControllerFilter.java:88)
	at com.stormpath.sdk.servlet.filter.HttpFilter.doFilter(HttpFilter.java:249)
	at com.stormpath.sdk.servlet.filter.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:65)
	at com.stormpath.sdk.servlet.filter.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:60)
	at com.stormpath.sdk.servlet.filter.account.AccountResolverFilter.filter(AccountResolverFilter.java:126)
	at com.stormpath.sdk.servlet.filter.HttpFilter.doFilter(HttpFilter.java:249)
	at com.stormpath.sdk.servlet.filter.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:65)
	at com.stormpath.sdk.servlet.filter.StormpathFilter.filter(StormpathFilter.java:124)
	at com.stormpath.sdk.servlet.filter.HttpFilter.doFilter(HttpFilter.java:249)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.pharmgkb.web.filter.RootFilter.doFilterInternal(RootFilter.java:67)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.pharmgkb.web.common.filters.LogFilter.doFilterInternal(LogFilter.java:50)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:192)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2500)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: Unable to publish request event: null
	at com.stormpath.sdk.servlet.http.impl.StormpathHttpServletRequest.publish(StormpathHttpServletRequest.java:401)
	at com.stormpath.sdk.servlet.http.impl.StormpathHttpServletRequest.logout(StormpathHttpServletRequest.java:417)
	at com.stormpath.sdk.servlet.mvc.LogoutController.handleRequest(LogoutController.java:55)
	at com.stormpath.sdk.servlet.filter.mvc.ControllerFilter.filter(ControllerFilter.java:86)
	... 33 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.stormpath.sdk.servlet.event.TokenRevocationRequestEventListener.on(TokenRevocationRequestEventListener.java:97)
	at com.stormpath.sdk.servlet.authc.impl.DefaultLogoutRequestEvent.accept(DefaultLogoutRequestEvent.java:45)
	at com.stormpath.sdk.servlet.event.impl.RequestEventPublisher.publish(RequestEventPublisher.java:50)
	at com.stormpath.sdk.servlet.event.impl.RequestEventPublisher.publish(RequestEventPublisher.java:28)
	at com.stormpath.sdk.servlet.http.impl.StormpathHttpServletRequest.publish(StormpathHttpServletRequest.java:398)
	... 36 common frames omitted
```

Behavior seems to be user dependent.  For some users it always happens, for others it never happens.

**Comment by mrioan** [comment]
@markwoon 

Line 97 of `TokenRevocationRequestEventListener.java` is:

```
log.debug("The current access and refresh tokens for {} have been revoked.", event.getAccount().getEmail());
```

It seems that `event.getAccount()` is null in some particular scenario.

Is this NPE preventing your specific operation to function properly? I would like to understand the severity of this issue. Is it a showstopper for you or you can simply catch it and continue as usual?

Thanks for reporting this!

**Comment by markwoon** [comment]
It's throwing that exception so users get a 500 when logging out.

Not a security issue but a usability one.

-Mark

**Comment by markwoon** [comment]
I can't really catch it easily add it is thrown by the servlet filter.

-Mark

**Comment by mrioan** [comment]
Hey @markwoon the simplest solution right now until we can solve this issue is to disable `DEBUG` for that particular class. Simply add the following line to your `logback.xml` file:

```
  <logger name="com.stormpath.sdk.servlet.event.TokenRevocationRequestEventListener" level="INFO"/>
```

Could you please confirm is that fixes the NPE?

Thanks

**Comment by markwoon** [comment]
It won't. You removed the check in the last commit so it will always
evaluate the argument and cause the NPE.

I'm just going to downgrade for now.

-Mark

**Comment by mrioan** [comment]
Dropping  workaround here:

```
public class CustomTokenRevocationRequestEventListener extends TokenRevocationRequestEventListener {

    @Override
    public void on(LogoutRequestEvent event) {
        try {
            super.on(event);
        } catch (NullPointerException e) {
            //https://github.com/stormpath/stormpath-sdk-java/issues/611
            //Let's simply swallow this known issue...
        }
    }

}
```
and
```
@Configuration
public class CustomConfiguration {

    @Bean
    public Publisher<RequestEvent> stormpathRequestEventPublisher() {
        List<RequestEventListener> listeners = new ArrayList<RequestEventListener>();
        listeners.add(new CustomTokenRevocationRequestEventListener());
        listeners.add(new RequestEventListenerAdapter());
        return new RequestEventPublisher(listeners);
    }

}

```

**Comment by markwoon** [comment]
Simpler to revert to older version :)

-Mark

**Comment by dogeared** [comment]
NOTE: This issue does not occur with `1.0.RC9` and it does with `1.0.RC9.1`

To reproduce, fire up the `01-some-access-controls` in the tutorial section.

Then, hit: `http://localhost:8080/logout`.

You will see the following error:

```
2016-04-29 18:53:34.870 ERROR 33269 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Unable to invoke Stormpath core controller: Unable to publish request event: null] with root cause

java.lang.NullPointerException: null
	at com.stormpath.sdk.servlet.event.TokenRevocationRequestEventListener.on(TokenRevocationRequestEventListener.java:97) ~[stormpath-sdk-servlet-1.0.RC9.1.jar!/:1.0.RC9.1]
```

This only seems to happen when spring security is disabled in `application.properties`:

```
stormpath.spring.security.enabled = false
security.basic.enabled = false
```

**Comment by dogeared** [comment]
@markwoon - Just wanted to let you know that I just release 1.0.RC9.2 that addresses this issue.

**Comment by markwoon** [comment]
Thanks for the quick fix.
