### ISSUE TITLE
YAML config is not working in the classpath

### ISSUE THREAD

**Issue by mzumbadoate** [stormpath/stormpath-sdk-java#679]
In the Servlet example if I use stormpath.yaml (in resources) I got this exception starting the server

ERROR c.s.s.s.a.ApplicationLoader - Stormpath application initialization failed
java.lang.IllegalStateException: The application's stormpath.properties configuration does not have a stormpath.application.href property defined.  This property is required required when looking up an application by ServletContext and you have more than one application registered in Stormpath.  For example:

 # in stormpath.properties:
 stormpath.application.href = YOUR_STORMPATH_APPLICATION_HREF_HERE

	at com.stormpath.sdk.servlet.application.DefaultApplicationResolver.getApplication(DefaultApplicationResolver.java:101)
	at com.stormpath.sdk.servlet.application.ApplicationLoader.doGetApplication(ApplicationLoader.java:182)
	at com.stormpath.sdk.servlet.application.ApplicationLoader.getApplication(ApplicationLoader.java:109)
	at com.stormpath.sdk.servlet.application.DefaultApplicationLoaderListener.contextInitialized(DefaultApplicationLoaderListener.java:53)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Jun 06, 2016 9:15:16 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class com.stormpath.sdk.servlet.application.DefaultApplicationLoaderListener
java.lang.IllegalStateException: The application's stormpath.properties configuration does not have a stormpath.application.href property defined.  This property is required required when looking up an application by ServletContext and you have more than one application registered in Stormpath.  For example:

 # in stormpath.properties:
 stormpath.application.href = YOUR_STORMPATH_APPLICATION_HREF_HERE

	at com.stormpath.sdk.servlet.application.DefaultApplicationResolver.getApplication(DefaultApplicationResolver.java:101)
	at com.stormpath.sdk.servlet.application.ApplicationLoader.doGetApplication(ApplicationLoader.java:182)
	at com.stormpath.sdk.servlet.application.ApplicationLoader.getApplication(ApplicationLoader.java:109)
	at com.stormpath.sdk.servlet.application.DefaultApplicationLoaderListener.contextInitialized(DefaultApplicationLoaderListener.java:53)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jun 06, 2016 9:15:16 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Jun 06, 2016 9:15:16 AM org.apache.catalina.util.SessionIdGenerator createSecureRandom
INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [134] milliseconds.
Jun 06, 2016 9:15:16 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [] startup failed due to previous errors
Jun 06, 2016 9:15:16 AM org.apache.catalina.core.ApplicationContext log

**Comment by mzumbadoate** [comment]
stormpath.properties and stormpath.json both are working

**Comment by mzumbadoate** [comment]
the stormpath.yaml used is
stormpath:
  application:
    href: "https://api.stormpath.com/v1/applications/3vUlEVoGo44EyRiJAtOVJh"
  web:
    produces: "text/html"

**Comment by mzumbadoate** [comment]
In spring-webmvc I'm getting this error
ERROR [localhost-startStop-1] o.s.web.context.ContextLoader Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webAppConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.stormpath.sdk.application.Application com.stormpath.spring.examples.WebAppConfig.stormpathApplication; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'stormpathApplication' defined in class com.stormpath.spring.config.StormpathConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.stormpath.sdk.application.Application]: Factory method 'stormpathApplication' threw exception; nested exception is java.lang.IllegalStateException: A 'stormpath.application.href' property value must be configured if you have more than one application registered in Stormpath.
